### ISSUE TITLE
资源使用不受限，很可能耗尽资源

### ISSUE THREAD

**Issue by xbee** [ChengjinWu/filesha1#1]
资源使用不受限，很可能耗尽资源，比如：文件夹下有大量文件或者目录很深的情况

**Comment by ChengjinWu** [comment]
在目录的深度遍历过程中，如果目录符合Exclude规则，就剪去该分支，继续下一个分支。

**Comment by ChengjinWu** [comment]
在目录的深度遍历过程中，如果目录符合Exclude规则，就剪去该分支，继续下一个分支。 @xbee

**Comment by xbee** [comment]
walk如果是单个goroutine的话，那就效率不高，如果是每个目录一个goroutine的话，那就会出现产生大量goroutine的情况，这会导致资源被消耗过多

**Comment by ChengjinWu** [comment]
那就实现一个线程池，定义线程池中线程的最小数量和最大数量。
每个线程执行以下操作：
0，从任务队列获取任务。
1，遍历当前任务的根目录下的所有文件和目录，把符合规则的文件生成路径名、sha1、文件大小进行输出；把需要继续遍历的文件夹放进线程池的任务队列中。
